- hosts: localhost
  vars:
    ImageName: ""
    Namespace: ""
    imageTag: ""

  gather_facts: yes
  connection: local
  tasks:
    - name: Deploy EmployeeApp
      command: "/usr/local/bin/helm install employee-app-test ./employee-app-chart --set service.internalPort=8080 --namespace=employee-app"
      delegate_to: localhost
      ignore_errors: yes
    - name: Update EmployeeApp
      command: "/usr/local/bin/helm upgrade employee-app-test ./employee-app-chart --set service.internalPort=8080 --namespace=employee-app"
      delegate_to: localhost
      ignore_errors: yes
