- hosts: localhost
  vars:
    ImageName: ""
    Namespace: ""
    imageTag: ""

  gather_facts: yes
  connection: local
  tasks:
    - name: Deploy EmployeeApp
      command: "/usr/local/bin/kubectl apply -f employee-app.yaml --namespace=employee-app"
      delegate_to: localhost
      ignore_errors: yes
