apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: 192.168.43.55:8765/employee-app:1.0.${TAG}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: employee-app-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: employee-app
